NEXUS-29515 - At least skip trying to deploy a snapshot while this plugin cannot support it
sonatype/nxrm3-maven-plugin pull request #29
Opened 2021-11-16 16:27 UTC by stephenc

2021-11-22 15:35 UTC, thejosh00 commented
This looks useful. +1 from me

2021-11-26 09:28 UTC, ybulatnikov requested changes

2021-11-26 09:28 UTC, ybulatnikov commented on maven-plugin/src/main/java/org/sonatype/nexus/maven/staging/PrepareDeployMojo.java
> +package org.sonatype.nexus.maven.staging;
License header is missing. Please run this command to add the header: `./headers.sh format`

2022-05-17 09:53 UTC, bobotimi commented
This PR has been open for six months, is it still needed?

2022-05-17 10:30 UTC, stephenc commented
Yes still required for us at least. Impossible to have deploy work for both
-SNAPSHOT and releases from the regular command line of `mvn deploy`
without this or an equivalent solutuion

On Tue, 17 May 2022 at 10:54, Olu Shiyanbade ***@***.***>
wrote:

> This PR has been open for six months, is it still needed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sonatype/nxrm3-maven-plugin/pull/29#issuecomment-1128663917>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABTDOFNZVD6EYIB6JRXWFDVKNUEDANCNFSM5IEWMANA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-25 16:55 UTC, tsawan commented
@stephenc can you sign the CLA so we can proceed to merge this PR? https://sonatypecla.herokuapp.com/sign-cla

2022-11-26 00:03 UTC, stephenc commented
![image](https://user-images.githubusercontent.com/209336/204064272-910c1ddd-5ac9-4f4e-9ebc-3974f8d9b274.jpeg)

It won't let me sign it again

2022-11-26 10:25 UTC, stephenc commented
As it it's been signed for over a year now, so I don't see what the block is

2022-11-26 10:28 UTC, stephenc commented
@brianf how long does it take you guys to merge a PR! Feel free to rework this PR as you see fit.

2022-11-28 15:32 UTC, tsawan commented
merged and released 1.0.6

2022-11-28 15:42 UTC, closed without merging